# Generated by Django 5.0.4 on 2024-04-27 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numInside', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Deleted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numInside', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Highlighted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numInside', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numInside', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='mail',
            name='isArchived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mail',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mail',
            name='isHighlighted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mail',
            name='isResponse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mail',
            name='isSelected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mail',
            name='isUnread',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mail',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mail',
            name='content',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Boxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archiveBox', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.archive')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('deletedBox', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.deleted')),
                ('highlightedBox', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.highlighted')),
                ('inboxBox', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.inbox')),
            ],
        ),
        migrations.AddField(
            model_name='mail',
            name='currentBox',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.inbox'),
        ),
    ]
