# Generated by Django 5.0.4 on 2024-04-28 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_mail_receiver_alter_mail_sender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mail',
            options={'ordering': ['-sentDate', 'title']},
        ),
        migrations.AddField(
            model_name='mail',
            name='responseContent',
            field=models.TextField(null=True),
        ),
    ]
