# Generated by Django 5.0.4 on 2024-04-29 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_mail_previouscontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='name',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
