# Generated by Django 5.0.4 on 2024-04-30 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_box_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='previousContent',
        ),
        migrations.AddField(
            model_name='mail',
            name='previousMail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.mail'),
        ),
    ]
