# Generated by Django 5.0.4 on 2024-04-30 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_mail_previouscontent_mail_previousmail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='isArchived',
        ),
        migrations.RemoveField(
            model_name='mail',
            name='isDeleted',
        ),
        migrations.RemoveField(
            model_name='mail',
            name='isHighlighted',
        ),
    ]
