# Generated by Django 5.0.4 on 2024-05-01 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_mail_isarchived_remove_mail_isdeleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='inShadowRealm',
            field=models.BooleanField(default=False),
        ),
    ]
